/*
PriceList Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricelist

import (
	"encoding/json"
)

// checks if the PricelistListPriceListsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PricelistListPriceListsRequest{}

// PricelistListPriceListsRequest struct for PricelistListPriceListsRequest
type PricelistListPriceListsRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	PageSize *int64 `json:"pageSize,omitempty"`
	PageToken *string `json:"pageToken,omitempty"`
	SearchQuery *string `json:"searchQuery,omitempty"`
	FilterMask *string `json:"filterMask,omitempty"`
	Filter *ListPriceListsRequestFilter `json:"filter,omitempty"`
}

// NewPricelistListPriceListsRequest instantiates a new PricelistListPriceListsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPricelistListPriceListsRequest() *PricelistListPriceListsRequest {
	this := PricelistListPriceListsRequest{}
	return &this
}

// NewPricelistListPriceListsRequestWithDefaults instantiates a new PricelistListPriceListsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPricelistListPriceListsRequestWithDefaults() *PricelistListPriceListsRequest {
	this := PricelistListPriceListsRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *PricelistListPriceListsRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistListPriceListsRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *PricelistListPriceListsRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *PricelistListPriceListsRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *PricelistListPriceListsRequest) GetPageSize() int64 {
	if o == nil || IsNil(o.PageSize) {
		var ret int64
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistListPriceListsRequest) GetPageSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *PricelistListPriceListsRequest) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int64 and assigns it to the PageSize field.
func (o *PricelistListPriceListsRequest) SetPageSize(v int64) {
	o.PageSize = &v
}

// GetPageToken returns the PageToken field value if set, zero value otherwise.
func (o *PricelistListPriceListsRequest) GetPageToken() string {
	if o == nil || IsNil(o.PageToken) {
		var ret string
		return ret
	}
	return *o.PageToken
}

// GetPageTokenOk returns a tuple with the PageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistListPriceListsRequest) GetPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.PageToken) {
		return nil, false
	}
	return o.PageToken, true
}

// HasPageToken returns a boolean if a field has been set.
func (o *PricelistListPriceListsRequest) HasPageToken() bool {
	if o != nil && !IsNil(o.PageToken) {
		return true
	}

	return false
}

// SetPageToken gets a reference to the given string and assigns it to the PageToken field.
func (o *PricelistListPriceListsRequest) SetPageToken(v string) {
	o.PageToken = &v
}

// GetSearchQuery returns the SearchQuery field value if set, zero value otherwise.
func (o *PricelistListPriceListsRequest) GetSearchQuery() string {
	if o == nil || IsNil(o.SearchQuery) {
		var ret string
		return ret
	}
	return *o.SearchQuery
}

// GetSearchQueryOk returns a tuple with the SearchQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistListPriceListsRequest) GetSearchQueryOk() (*string, bool) {
	if o == nil || IsNil(o.SearchQuery) {
		return nil, false
	}
	return o.SearchQuery, true
}

// HasSearchQuery returns a boolean if a field has been set.
func (o *PricelistListPriceListsRequest) HasSearchQuery() bool {
	if o != nil && !IsNil(o.SearchQuery) {
		return true
	}

	return false
}

// SetSearchQuery gets a reference to the given string and assigns it to the SearchQuery field.
func (o *PricelistListPriceListsRequest) SetSearchQuery(v string) {
	o.SearchQuery = &v
}

// GetFilterMask returns the FilterMask field value if set, zero value otherwise.
func (o *PricelistListPriceListsRequest) GetFilterMask() string {
	if o == nil || IsNil(o.FilterMask) {
		var ret string
		return ret
	}
	return *o.FilterMask
}

// GetFilterMaskOk returns a tuple with the FilterMask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistListPriceListsRequest) GetFilterMaskOk() (*string, bool) {
	if o == nil || IsNil(o.FilterMask) {
		return nil, false
	}
	return o.FilterMask, true
}

// HasFilterMask returns a boolean if a field has been set.
func (o *PricelistListPriceListsRequest) HasFilterMask() bool {
	if o != nil && !IsNil(o.FilterMask) {
		return true
	}

	return false
}

// SetFilterMask gets a reference to the given string and assigns it to the FilterMask field.
func (o *PricelistListPriceListsRequest) SetFilterMask(v string) {
	o.FilterMask = &v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *PricelistListPriceListsRequest) GetFilter() ListPriceListsRequestFilter {
	if o == nil || IsNil(o.Filter) {
		var ret ListPriceListsRequestFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistListPriceListsRequest) GetFilterOk() (*ListPriceListsRequestFilter, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *PricelistListPriceListsRequest) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given ListPriceListsRequestFilter and assigns it to the Filter field.
func (o *PricelistListPriceListsRequest) SetFilter(v ListPriceListsRequestFilter) {
	o.Filter = &v
}

func (o PricelistListPriceListsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PricelistListPriceListsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.PageSize) {
		toSerialize["pageSize"] = o.PageSize
	}
	if !IsNil(o.PageToken) {
		toSerialize["pageToken"] = o.PageToken
	}
	if !IsNil(o.SearchQuery) {
		toSerialize["searchQuery"] = o.SearchQuery
	}
	if !IsNil(o.FilterMask) {
		toSerialize["filterMask"] = o.FilterMask
	}
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	return toSerialize, nil
}

type NullablePricelistListPriceListsRequest struct {
	value *PricelistListPriceListsRequest
	isSet bool
}

func (v NullablePricelistListPriceListsRequest) Get() *PricelistListPriceListsRequest {
	return v.value
}

func (v *NullablePricelistListPriceListsRequest) Set(val *PricelistListPriceListsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePricelistListPriceListsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePricelistListPriceListsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePricelistListPriceListsRequest(val *PricelistListPriceListsRequest) *NullablePricelistListPriceListsRequest {
	return &NullablePricelistListPriceListsRequest{value: val, isSet: true}
}

func (v NullablePricelistListPriceListsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePricelistListPriceListsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


