/*
PriceList Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricelist

import (
	"encoding/json"
)

// checks if the PricelistGetPriceListByCodeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PricelistGetPriceListByCodeRequest{}

// PricelistGetPriceListByCodeRequest struct for PricelistGetPriceListByCodeRequest
type PricelistGetPriceListByCodeRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	Code *string `json:"code,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PricelistGetPriceListByCodeRequest PricelistGetPriceListByCodeRequest

// NewPricelistGetPriceListByCodeRequest instantiates a new PricelistGetPriceListByCodeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPricelistGetPriceListByCodeRequest() *PricelistGetPriceListByCodeRequest {
	this := PricelistGetPriceListByCodeRequest{}
	return &this
}

// NewPricelistGetPriceListByCodeRequestWithDefaults instantiates a new PricelistGetPriceListByCodeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPricelistGetPriceListByCodeRequestWithDefaults() *PricelistGetPriceListByCodeRequest {
	this := PricelistGetPriceListByCodeRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *PricelistGetPriceListByCodeRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeRequest) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeRequest) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeRequest) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *PricelistGetPriceListByCodeRequest) SetCode(v string) {
	o.Code = &v
}

func (o PricelistGetPriceListByCodeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PricelistGetPriceListByCodeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PricelistGetPriceListByCodeRequest) UnmarshalJSON(data []byte) (err error) {
	varPricelistGetPriceListByCodeRequest := _PricelistGetPriceListByCodeRequest{}

	err = json.Unmarshal(data, &varPricelistGetPriceListByCodeRequest)

	if err != nil {
		return err
	}

	*o = PricelistGetPriceListByCodeRequest(varPricelistGetPriceListByCodeRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "code")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PricelistGetPriceListByCodeRequest) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *PricelistGetPriceListByCodeRequest) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullablePricelistGetPriceListByCodeRequest struct {
	value *PricelistGetPriceListByCodeRequest
	isSet bool
}

func (v NullablePricelistGetPriceListByCodeRequest) Get() *PricelistGetPriceListByCodeRequest {
	return v.value
}

func (v *NullablePricelistGetPriceListByCodeRequest) Set(val *PricelistGetPriceListByCodeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePricelistGetPriceListByCodeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePricelistGetPriceListByCodeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePricelistGetPriceListByCodeRequest(val *PricelistGetPriceListByCodeRequest) *NullablePricelistGetPriceListByCodeRequest {
	return &NullablePricelistGetPriceListByCodeRequest{value: val, isSet: true}
}

func (v NullablePricelistGetPriceListByCodeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePricelistGetPriceListByCodeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


