/*
pricelist/service.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricelist

import (
	"encoding/json"
)

// checks if the PricelistGetFullPriceItemsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PricelistGetFullPriceItemsResponse{}

// PricelistGetFullPriceItemsResponse struct for PricelistGetFullPriceItemsResponse
type PricelistGetFullPriceItemsResponse struct {
	PriceItems []PricelistGetFullPriceItem `json:"priceItems,omitempty"`
}

// NewPricelistGetFullPriceItemsResponse instantiates a new PricelistGetFullPriceItemsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPricelistGetFullPriceItemsResponse() *PricelistGetFullPriceItemsResponse {
	this := PricelistGetFullPriceItemsResponse{}
	return &this
}

// NewPricelistGetFullPriceItemsResponseWithDefaults instantiates a new PricelistGetFullPriceItemsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPricelistGetFullPriceItemsResponseWithDefaults() *PricelistGetFullPriceItemsResponse {
	this := PricelistGetFullPriceItemsResponse{}
	return &this
}

// GetPriceItems returns the PriceItems field value if set, zero value otherwise.
func (o *PricelistGetFullPriceItemsResponse) GetPriceItems() []PricelistGetFullPriceItem {
	if o == nil || IsNil(o.PriceItems) {
		var ret []PricelistGetFullPriceItem
		return ret
	}
	return o.PriceItems
}

// GetPriceItemsOk returns a tuple with the PriceItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetFullPriceItemsResponse) GetPriceItemsOk() ([]PricelistGetFullPriceItem, bool) {
	if o == nil || IsNil(o.PriceItems) {
		return nil, false
	}
	return o.PriceItems, true
}

// HasPriceItems returns a boolean if a field has been set.
func (o *PricelistGetFullPriceItemsResponse) HasPriceItems() bool {
	if o != nil && !IsNil(o.PriceItems) {
		return true
	}

	return false
}

// SetPriceItems gets a reference to the given []PricelistGetFullPriceItem and assigns it to the PriceItems field.
func (o *PricelistGetFullPriceItemsResponse) SetPriceItems(v []PricelistGetFullPriceItem) {
	o.PriceItems = v
}

func (o PricelistGetFullPriceItemsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PricelistGetFullPriceItemsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PriceItems) {
		toSerialize["priceItems"] = o.PriceItems
	}
	return toSerialize, nil
}

type NullablePricelistGetFullPriceItemsResponse struct {
	value *PricelistGetFullPriceItemsResponse
	isSet bool
}

func (v NullablePricelistGetFullPriceItemsResponse) Get() *PricelistGetFullPriceItemsResponse {
	return v.value
}

func (v *NullablePricelistGetFullPriceItemsResponse) Set(val *PricelistGetFullPriceItemsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePricelistGetFullPriceItemsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePricelistGetFullPriceItemsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePricelistGetFullPriceItemsResponse(val *PricelistGetFullPriceItemsResponse) *NullablePricelistGetFullPriceItemsResponse {
	return &NullablePricelistGetFullPriceItemsResponse{value: val, isSet: true}
}

func (v NullablePricelistGetFullPriceItemsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePricelistGetFullPriceItemsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


