/*
PriceList Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricelist

import (
	"encoding/json"
	"time"
)

// checks if the PricelistSetPriceListItemPrice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PricelistSetPriceListItemPrice{}

// PricelistSetPriceListItemPrice struct for PricelistSetPriceListItemPrice
type PricelistSetPriceListItemPrice struct {
	Price *PricelistMoney `json:"price,omitempty"`
	IsEnabled *bool `json:"isEnabled,omitempty"`
	StartAt *time.Time `json:"startAt,omitempty"`
	EndAt *time.Time `json:"endAt,omitempty"`
	Order *int64 `json:"order,omitempty"`
	BasePrice *PricelistMoney `json:"basePrice,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PricelistSetPriceListItemPrice PricelistSetPriceListItemPrice

// NewPricelistSetPriceListItemPrice instantiates a new PricelistSetPriceListItemPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPricelistSetPriceListItemPrice() *PricelistSetPriceListItemPrice {
	this := PricelistSetPriceListItemPrice{}
	return &this
}

// NewPricelistSetPriceListItemPriceWithDefaults instantiates a new PricelistSetPriceListItemPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPricelistSetPriceListItemPriceWithDefaults() *PricelistSetPriceListItemPrice {
	this := PricelistSetPriceListItemPrice{}
	return &this
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *PricelistSetPriceListItemPrice) GetPrice() PricelistMoney {
	if o == nil || IsNil(o.Price) {
		var ret PricelistMoney
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistSetPriceListItemPrice) GetPriceOk() (*PricelistMoney, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *PricelistSetPriceListItemPrice) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given PricelistMoney and assigns it to the Price field.
func (o *PricelistSetPriceListItemPrice) SetPrice(v PricelistMoney) {
	o.Price = &v
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise.
func (o *PricelistSetPriceListItemPrice) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled) {
		var ret bool
		return ret
	}
	return *o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistSetPriceListItemPrice) GetIsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnabled) {
		return nil, false
	}
	return o.IsEnabled, true
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *PricelistSetPriceListItemPrice) HasIsEnabled() bool {
	if o != nil && !IsNil(o.IsEnabled) {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given bool and assigns it to the IsEnabled field.
func (o *PricelistSetPriceListItemPrice) SetIsEnabled(v bool) {
	o.IsEnabled = &v
}

// GetStartAt returns the StartAt field value if set, zero value otherwise.
func (o *PricelistSetPriceListItemPrice) GetStartAt() time.Time {
	if o == nil || IsNil(o.StartAt) {
		var ret time.Time
		return ret
	}
	return *o.StartAt
}

// GetStartAtOk returns a tuple with the StartAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistSetPriceListItemPrice) GetStartAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartAt) {
		return nil, false
	}
	return o.StartAt, true
}

// HasStartAt returns a boolean if a field has been set.
func (o *PricelistSetPriceListItemPrice) HasStartAt() bool {
	if o != nil && !IsNil(o.StartAt) {
		return true
	}

	return false
}

// SetStartAt gets a reference to the given time.Time and assigns it to the StartAt field.
func (o *PricelistSetPriceListItemPrice) SetStartAt(v time.Time) {
	o.StartAt = &v
}

// GetEndAt returns the EndAt field value if set, zero value otherwise.
func (o *PricelistSetPriceListItemPrice) GetEndAt() time.Time {
	if o == nil || IsNil(o.EndAt) {
		var ret time.Time
		return ret
	}
	return *o.EndAt
}

// GetEndAtOk returns a tuple with the EndAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistSetPriceListItemPrice) GetEndAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndAt) {
		return nil, false
	}
	return o.EndAt, true
}

// HasEndAt returns a boolean if a field has been set.
func (o *PricelistSetPriceListItemPrice) HasEndAt() bool {
	if o != nil && !IsNil(o.EndAt) {
		return true
	}

	return false
}

// SetEndAt gets a reference to the given time.Time and assigns it to the EndAt field.
func (o *PricelistSetPriceListItemPrice) SetEndAt(v time.Time) {
	o.EndAt = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *PricelistSetPriceListItemPrice) GetOrder() int64 {
	if o == nil || IsNil(o.Order) {
		var ret int64
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistSetPriceListItemPrice) GetOrderOk() (*int64, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *PricelistSetPriceListItemPrice) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int64 and assigns it to the Order field.
func (o *PricelistSetPriceListItemPrice) SetOrder(v int64) {
	o.Order = &v
}

// GetBasePrice returns the BasePrice field value if set, zero value otherwise.
func (o *PricelistSetPriceListItemPrice) GetBasePrice() PricelistMoney {
	if o == nil || IsNil(o.BasePrice) {
		var ret PricelistMoney
		return ret
	}
	return *o.BasePrice
}

// GetBasePriceOk returns a tuple with the BasePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistSetPriceListItemPrice) GetBasePriceOk() (*PricelistMoney, bool) {
	if o == nil || IsNil(o.BasePrice) {
		return nil, false
	}
	return o.BasePrice, true
}

// HasBasePrice returns a boolean if a field has been set.
func (o *PricelistSetPriceListItemPrice) HasBasePrice() bool {
	if o != nil && !IsNil(o.BasePrice) {
		return true
	}

	return false
}

// SetBasePrice gets a reference to the given PricelistMoney and assigns it to the BasePrice field.
func (o *PricelistSetPriceListItemPrice) SetBasePrice(v PricelistMoney) {
	o.BasePrice = &v
}

func (o PricelistSetPriceListItemPrice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PricelistSetPriceListItemPrice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.IsEnabled) {
		toSerialize["isEnabled"] = o.IsEnabled
	}
	if !IsNil(o.StartAt) {
		toSerialize["startAt"] = o.StartAt
	}
	if !IsNil(o.EndAt) {
		toSerialize["endAt"] = o.EndAt
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.BasePrice) {
		toSerialize["basePrice"] = o.BasePrice
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PricelistSetPriceListItemPrice) UnmarshalJSON(data []byte) (err error) {
	varPricelistSetPriceListItemPrice := _PricelistSetPriceListItemPrice{}

	err = json.Unmarshal(data, &varPricelistSetPriceListItemPrice)

	if err != nil {
		return err
	}

	*o = PricelistSetPriceListItemPrice(varPricelistSetPriceListItemPrice)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "price")
		delete(additionalProperties, "isEnabled")
		delete(additionalProperties, "startAt")
		delete(additionalProperties, "endAt")
		delete(additionalProperties, "order")
		delete(additionalProperties, "basePrice")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PricelistSetPriceListItemPrice) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *PricelistSetPriceListItemPrice) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullablePricelistSetPriceListItemPrice struct {
	value *PricelistSetPriceListItemPrice
	isSet bool
}

func (v NullablePricelistSetPriceListItemPrice) Get() *PricelistSetPriceListItemPrice {
	return v.value
}

func (v *NullablePricelistSetPriceListItemPrice) Set(val *PricelistSetPriceListItemPrice) {
	v.value = val
	v.isSet = true
}

func (v NullablePricelistSetPriceListItemPrice) IsSet() bool {
	return v.isSet
}

func (v *NullablePricelistSetPriceListItemPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePricelistSetPriceListItemPrice(val *PricelistSetPriceListItemPrice) *NullablePricelistSetPriceListItemPrice {
	return &NullablePricelistSetPriceListItemPrice{value: val, isSet: true}
}

func (v NullablePricelistSetPriceListItemPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePricelistSetPriceListItemPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


