/*
pricelist/service.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricelist

import (
	"encoding/json"
)

// checks if the PricelistGetPriceItemsByPriceListItemIdsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PricelistGetPriceItemsByPriceListItemIdsResponse{}

// PricelistGetPriceItemsByPriceListItemIdsResponse struct for PricelistGetPriceItemsByPriceListItemIdsResponse
type PricelistGetPriceItemsByPriceListItemIdsResponse struct {
	Prices []PricelistGetPriceListItem `json:"prices,omitempty"`
}

// NewPricelistGetPriceItemsByPriceListItemIdsResponse instantiates a new PricelistGetPriceItemsByPriceListItemIdsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPricelistGetPriceItemsByPriceListItemIdsResponse() *PricelistGetPriceItemsByPriceListItemIdsResponse {
	this := PricelistGetPriceItemsByPriceListItemIdsResponse{}
	return &this
}

// NewPricelistGetPriceItemsByPriceListItemIdsResponseWithDefaults instantiates a new PricelistGetPriceItemsByPriceListItemIdsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPricelistGetPriceItemsByPriceListItemIdsResponseWithDefaults() *PricelistGetPriceItemsByPriceListItemIdsResponse {
	this := PricelistGetPriceItemsByPriceListItemIdsResponse{}
	return &this
}

// GetPrices returns the Prices field value if set, zero value otherwise.
func (o *PricelistGetPriceItemsByPriceListItemIdsResponse) GetPrices() []PricelistGetPriceListItem {
	if o == nil || IsNil(o.Prices) {
		var ret []PricelistGetPriceListItem
		return ret
	}
	return o.Prices
}

// GetPricesOk returns a tuple with the Prices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceItemsByPriceListItemIdsResponse) GetPricesOk() ([]PricelistGetPriceListItem, bool) {
	if o == nil || IsNil(o.Prices) {
		return nil, false
	}
	return o.Prices, true
}

// HasPrices returns a boolean if a field has been set.
func (o *PricelistGetPriceItemsByPriceListItemIdsResponse) HasPrices() bool {
	if o != nil && !IsNil(o.Prices) {
		return true
	}

	return false
}

// SetPrices gets a reference to the given []PricelistGetPriceListItem and assigns it to the Prices field.
func (o *PricelistGetPriceItemsByPriceListItemIdsResponse) SetPrices(v []PricelistGetPriceListItem) {
	o.Prices = v
}

func (o PricelistGetPriceItemsByPriceListItemIdsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PricelistGetPriceItemsByPriceListItemIdsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Prices) {
		toSerialize["prices"] = o.Prices
	}
	return toSerialize, nil
}

type NullablePricelistGetPriceItemsByPriceListItemIdsResponse struct {
	value *PricelistGetPriceItemsByPriceListItemIdsResponse
	isSet bool
}

func (v NullablePricelistGetPriceItemsByPriceListItemIdsResponse) Get() *PricelistGetPriceItemsByPriceListItemIdsResponse {
	return v.value
}

func (v *NullablePricelistGetPriceItemsByPriceListItemIdsResponse) Set(val *PricelistGetPriceItemsByPriceListItemIdsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePricelistGetPriceItemsByPriceListItemIdsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePricelistGetPriceItemsByPriceListItemIdsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePricelistGetPriceItemsByPriceListItemIdsResponse(val *PricelistGetPriceItemsByPriceListItemIdsResponse) *NullablePricelistGetPriceItemsByPriceListItemIdsResponse {
	return &NullablePricelistGetPriceItemsByPriceListItemIdsResponse{value: val, isSet: true}
}

func (v NullablePricelistGetPriceItemsByPriceListItemIdsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePricelistGetPriceItemsByPriceListItemIdsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


