/*
PriceList Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricelist

import (
	"encoding/json"
	"time"
)

// checks if the PricelistGetPriceListByCodeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PricelistGetPriceListByCodeResponse{}

// PricelistGetPriceListByCodeResponse struct for PricelistGetPriceListByCodeResponse
type PricelistGetPriceListByCodeResponse struct {
	Id *string `json:"id,omitempty"`
	Grn *string `json:"grn,omitempty"`
	Code *string `json:"code,omitempty"`
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	IsActive *bool `json:"isActive,omitempty"`
	IsDefault *bool `json:"isDefault,omitempty"`
	Currency *PricelistCurrency `json:"currency,omitempty"`
	VatIncluded *bool `json:"vatIncluded,omitempty"`
	DeliveredDutyPaid *bool `json:"deliveredDutyPaid,omitempty"`
	Segments []string `json:"segments,omitempty"`
	Markets []string `json:"markets,omitempty"`
	Channels []string `json:"channels,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	Type *PricelistPriceListType `json:"type,omitempty"`
	IsSystem *bool `json:"isSystem,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PricelistGetPriceListByCodeResponse PricelistGetPriceListByCodeResponse

// NewPricelistGetPriceListByCodeResponse instantiates a new PricelistGetPriceListByCodeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPricelistGetPriceListByCodeResponse() *PricelistGetPriceListByCodeResponse {
	this := PricelistGetPriceListByCodeResponse{}
	var currency PricelistCurrency = PRICELISTCURRENCY_XXX
	this.Currency = &currency
	var type_ PricelistPriceListType = PRICELISTPRICELISTTYPE_UNKNOWN
	this.Type = &type_
	return &this
}

// NewPricelistGetPriceListByCodeResponseWithDefaults instantiates a new PricelistGetPriceListByCodeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPricelistGetPriceListByCodeResponseWithDefaults() *PricelistGetPriceListByCodeResponse {
	this := PricelistGetPriceListByCodeResponse{}
	var currency PricelistCurrency = PRICELISTCURRENCY_XXX
	this.Currency = &currency
	var type_ PricelistPriceListType = PRICELISTPRICELISTTYPE_UNKNOWN
	this.Type = &type_
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PricelistGetPriceListByCodeResponse) SetId(v string) {
	o.Id = &v
}

// GetGrn returns the Grn field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeResponse) GetGrn() string {
	if o == nil || IsNil(o.Grn) {
		var ret string
		return ret
	}
	return *o.Grn
}

// GetGrnOk returns a tuple with the Grn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeResponse) GetGrnOk() (*string, bool) {
	if o == nil || IsNil(o.Grn) {
		return nil, false
	}
	return o.Grn, true
}

// HasGrn returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeResponse) HasGrn() bool {
	if o != nil && !IsNil(o.Grn) {
		return true
	}

	return false
}

// SetGrn gets a reference to the given string and assigns it to the Grn field.
func (o *PricelistGetPriceListByCodeResponse) SetGrn(v string) {
	o.Grn = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeResponse) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeResponse) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *PricelistGetPriceListByCodeResponse) SetCode(v string) {
	o.Code = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PricelistGetPriceListByCodeResponse) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PricelistGetPriceListByCodeResponse) SetDescription(v string) {
	o.Description = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeResponse) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeResponse) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeResponse) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *PricelistGetPriceListByCodeResponse) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetIsDefault returns the IsDefault field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeResponse) GetIsDefault() bool {
	if o == nil || IsNil(o.IsDefault) {
		var ret bool
		return ret
	}
	return *o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeResponse) GetIsDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDefault) {
		return nil, false
	}
	return o.IsDefault, true
}

// HasIsDefault returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeResponse) HasIsDefault() bool {
	if o != nil && !IsNil(o.IsDefault) {
		return true
	}

	return false
}

// SetIsDefault gets a reference to the given bool and assigns it to the IsDefault field.
func (o *PricelistGetPriceListByCodeResponse) SetIsDefault(v bool) {
	o.IsDefault = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeResponse) GetCurrency() PricelistCurrency {
	if o == nil || IsNil(o.Currency) {
		var ret PricelistCurrency
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeResponse) GetCurrencyOk() (*PricelistCurrency, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeResponse) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given PricelistCurrency and assigns it to the Currency field.
func (o *PricelistGetPriceListByCodeResponse) SetCurrency(v PricelistCurrency) {
	o.Currency = &v
}

// GetVatIncluded returns the VatIncluded field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeResponse) GetVatIncluded() bool {
	if o == nil || IsNil(o.VatIncluded) {
		var ret bool
		return ret
	}
	return *o.VatIncluded
}

// GetVatIncludedOk returns a tuple with the VatIncluded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeResponse) GetVatIncludedOk() (*bool, bool) {
	if o == nil || IsNil(o.VatIncluded) {
		return nil, false
	}
	return o.VatIncluded, true
}

// HasVatIncluded returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeResponse) HasVatIncluded() bool {
	if o != nil && !IsNil(o.VatIncluded) {
		return true
	}

	return false
}

// SetVatIncluded gets a reference to the given bool and assigns it to the VatIncluded field.
func (o *PricelistGetPriceListByCodeResponse) SetVatIncluded(v bool) {
	o.VatIncluded = &v
}

// GetDeliveredDutyPaid returns the DeliveredDutyPaid field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeResponse) GetDeliveredDutyPaid() bool {
	if o == nil || IsNil(o.DeliveredDutyPaid) {
		var ret bool
		return ret
	}
	return *o.DeliveredDutyPaid
}

// GetDeliveredDutyPaidOk returns a tuple with the DeliveredDutyPaid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeResponse) GetDeliveredDutyPaidOk() (*bool, bool) {
	if o == nil || IsNil(o.DeliveredDutyPaid) {
		return nil, false
	}
	return o.DeliveredDutyPaid, true
}

// HasDeliveredDutyPaid returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeResponse) HasDeliveredDutyPaid() bool {
	if o != nil && !IsNil(o.DeliveredDutyPaid) {
		return true
	}

	return false
}

// SetDeliveredDutyPaid gets a reference to the given bool and assigns it to the DeliveredDutyPaid field.
func (o *PricelistGetPriceListByCodeResponse) SetDeliveredDutyPaid(v bool) {
	o.DeliveredDutyPaid = &v
}

// GetSegments returns the Segments field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeResponse) GetSegments() []string {
	if o == nil || IsNil(o.Segments) {
		var ret []string
		return ret
	}
	return o.Segments
}

// GetSegmentsOk returns a tuple with the Segments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeResponse) GetSegmentsOk() ([]string, bool) {
	if o == nil || IsNil(o.Segments) {
		return nil, false
	}
	return o.Segments, true
}

// HasSegments returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeResponse) HasSegments() bool {
	if o != nil && !IsNil(o.Segments) {
		return true
	}

	return false
}

// SetSegments gets a reference to the given []string and assigns it to the Segments field.
func (o *PricelistGetPriceListByCodeResponse) SetSegments(v []string) {
	o.Segments = v
}

// GetMarkets returns the Markets field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeResponse) GetMarkets() []string {
	if o == nil || IsNil(o.Markets) {
		var ret []string
		return ret
	}
	return o.Markets
}

// GetMarketsOk returns a tuple with the Markets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeResponse) GetMarketsOk() ([]string, bool) {
	if o == nil || IsNil(o.Markets) {
		return nil, false
	}
	return o.Markets, true
}

// HasMarkets returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeResponse) HasMarkets() bool {
	if o != nil && !IsNil(o.Markets) {
		return true
	}

	return false
}

// SetMarkets gets a reference to the given []string and assigns it to the Markets field.
func (o *PricelistGetPriceListByCodeResponse) SetMarkets(v []string) {
	o.Markets = v
}

// GetChannels returns the Channels field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeResponse) GetChannels() []string {
	if o == nil || IsNil(o.Channels) {
		var ret []string
		return ret
	}
	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeResponse) GetChannelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Channels) {
		return nil, false
	}
	return o.Channels, true
}

// HasChannels returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeResponse) HasChannels() bool {
	if o != nil && !IsNil(o.Channels) {
		return true
	}

	return false
}

// SetChannels gets a reference to the given []string and assigns it to the Channels field.
func (o *PricelistGetPriceListByCodeResponse) SetChannels(v []string) {
	o.Channels = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeResponse) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *PricelistGetPriceListByCodeResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeResponse) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *PricelistGetPriceListByCodeResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeResponse) GetType() PricelistPriceListType {
	if o == nil || IsNil(o.Type) {
		var ret PricelistPriceListType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeResponse) GetTypeOk() (*PricelistPriceListType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeResponse) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given PricelistPriceListType and assigns it to the Type field.
func (o *PricelistGetPriceListByCodeResponse) SetType(v PricelistPriceListType) {
	o.Type = &v
}

// GetIsSystem returns the IsSystem field value if set, zero value otherwise.
func (o *PricelistGetPriceListByCodeResponse) GetIsSystem() bool {
	if o == nil || IsNil(o.IsSystem) {
		var ret bool
		return ret
	}
	return *o.IsSystem
}

// GetIsSystemOk returns a tuple with the IsSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListByCodeResponse) GetIsSystemOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSystem) {
		return nil, false
	}
	return o.IsSystem, true
}

// HasIsSystem returns a boolean if a field has been set.
func (o *PricelistGetPriceListByCodeResponse) HasIsSystem() bool {
	if o != nil && !IsNil(o.IsSystem) {
		return true
	}

	return false
}

// SetIsSystem gets a reference to the given bool and assigns it to the IsSystem field.
func (o *PricelistGetPriceListByCodeResponse) SetIsSystem(v bool) {
	o.IsSystem = &v
}

func (o PricelistGetPriceListByCodeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PricelistGetPriceListByCodeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Grn) {
		toSerialize["grn"] = o.Grn
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.IsActive) {
		toSerialize["isActive"] = o.IsActive
	}
	if !IsNil(o.IsDefault) {
		toSerialize["isDefault"] = o.IsDefault
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.VatIncluded) {
		toSerialize["vatIncluded"] = o.VatIncluded
	}
	if !IsNil(o.DeliveredDutyPaid) {
		toSerialize["deliveredDutyPaid"] = o.DeliveredDutyPaid
	}
	if !IsNil(o.Segments) {
		toSerialize["segments"] = o.Segments
	}
	if !IsNil(o.Markets) {
		toSerialize["markets"] = o.Markets
	}
	if !IsNil(o.Channels) {
		toSerialize["channels"] = o.Channels
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.IsSystem) {
		toSerialize["isSystem"] = o.IsSystem
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PricelistGetPriceListByCodeResponse) UnmarshalJSON(data []byte) (err error) {
	varPricelistGetPriceListByCodeResponse := _PricelistGetPriceListByCodeResponse{}

	err = json.Unmarshal(data, &varPricelistGetPriceListByCodeResponse)

	if err != nil {
		return err
	}

	*o = PricelistGetPriceListByCodeResponse(varPricelistGetPriceListByCodeResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "grn")
		delete(additionalProperties, "code")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "isActive")
		delete(additionalProperties, "isDefault")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "vatIncluded")
		delete(additionalProperties, "deliveredDutyPaid")
		delete(additionalProperties, "segments")
		delete(additionalProperties, "markets")
		delete(additionalProperties, "channels")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "type")
		delete(additionalProperties, "isSystem")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PricelistGetPriceListByCodeResponse) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *PricelistGetPriceListByCodeResponse) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullablePricelistGetPriceListByCodeResponse struct {
	value *PricelistGetPriceListByCodeResponse
	isSet bool
}

func (v NullablePricelistGetPriceListByCodeResponse) Get() *PricelistGetPriceListByCodeResponse {
	return v.value
}

func (v *NullablePricelistGetPriceListByCodeResponse) Set(val *PricelistGetPriceListByCodeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePricelistGetPriceListByCodeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePricelistGetPriceListByCodeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePricelistGetPriceListByCodeResponse(val *PricelistGetPriceListByCodeResponse) *NullablePricelistGetPriceListByCodeResponse {
	return &NullablePricelistGetPriceListByCodeResponse{value: val, isSet: true}
}

func (v NullablePricelistGetPriceListByCodeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePricelistGetPriceListByCodeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


