/*
pricelist/service.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricelist

import (
	"encoding/json"
	"fmt"
)

// PricelistCurrency Stands for Albania, not all ;-)
type PricelistCurrency string

// List of pricelistCurrency
const (
	XXX PricelistCurrency = "XXX"
	ALL PricelistCurrency = "ALL"
	DZD PricelistCurrency = "DZD"
	ARS PricelistCurrency = "ARS"
	AUD PricelistCurrency = "AUD"
	BSD PricelistCurrency = "BSD"
	BHD PricelistCurrency = "BHD"
	BDT PricelistCurrency = "BDT"
	AMD PricelistCurrency = "AMD"
	BBD PricelistCurrency = "BBD"
	BMD PricelistCurrency = "BMD"
	BTN PricelistCurrency = "BTN"
	BOB PricelistCurrency = "BOB"
	BWP PricelistCurrency = "BWP"
	BZD PricelistCurrency = "BZD"
	SBD PricelistCurrency = "SBD"
	BND PricelistCurrency = "BND"
	MMK PricelistCurrency = "MMK"
	BIF PricelistCurrency = "BIF"
	KHR PricelistCurrency = "KHR"
	CAD PricelistCurrency = "CAD"
	CVE PricelistCurrency = "CVE"
	KYD PricelistCurrency = "KYD"
	LKR PricelistCurrency = "LKR"
	CLP PricelistCurrency = "CLP"
	CNY PricelistCurrency = "CNY"
	COP PricelistCurrency = "COP"
	KMF PricelistCurrency = "KMF"
	CRC PricelistCurrency = "CRC"
	HRK PricelistCurrency = "HRK"
	CUP PricelistCurrency = "CUP"
	CZK PricelistCurrency = "CZK"
	DKK PricelistCurrency = "DKK"
	DOP PricelistCurrency = "DOP"
	SVC PricelistCurrency = "SVC"
	ETB PricelistCurrency = "ETB"
	ERN PricelistCurrency = "ERN"
	FKP PricelistCurrency = "FKP"
	FJD PricelistCurrency = "FJD"
	DJF PricelistCurrency = "DJF"
	GMD PricelistCurrency = "GMD"
	GIP PricelistCurrency = "GIP"
	GTQ PricelistCurrency = "GTQ"
	GNF PricelistCurrency = "GNF"
	GYD PricelistCurrency = "GYD"
	HTG PricelistCurrency = "HTG"
	HNL PricelistCurrency = "HNL"
	HKD PricelistCurrency = "HKD"
	HUF PricelistCurrency = "HUF"
	ISK PricelistCurrency = "ISK"
	INR PricelistCurrency = "INR"
	IDR PricelistCurrency = "IDR"
	IRR PricelistCurrency = "IRR"
	IQD PricelistCurrency = "IQD"
	ILS PricelistCurrency = "ILS"
	JMD PricelistCurrency = "JMD"
	JPY PricelistCurrency = "JPY"
	KZT PricelistCurrency = "KZT"
	JOD PricelistCurrency = "JOD"
	KES PricelistCurrency = "KES"
	KPW PricelistCurrency = "KPW"
	KRW PricelistCurrency = "KRW"
	KWD PricelistCurrency = "KWD"
	KGS PricelistCurrency = "KGS"
	LAK PricelistCurrency = "LAK"
	LBP PricelistCurrency = "LBP"
	LSL PricelistCurrency = "LSL"
	LRD PricelistCurrency = "LRD"
	LYD PricelistCurrency = "LYD"
	LTL PricelistCurrency = "LTL"
	MOP PricelistCurrency = "MOP"
	MWK PricelistCurrency = "MWK"
	MYR PricelistCurrency = "MYR"
	MVR PricelistCurrency = "MVR"
	MRO PricelistCurrency = "MRO"
	MUR PricelistCurrency = "MUR"
	MXN PricelistCurrency = "MXN"
	MNT PricelistCurrency = "MNT"
	MDL PricelistCurrency = "MDL"
	MAD PricelistCurrency = "MAD"
	OMR PricelistCurrency = "OMR"
	NAD PricelistCurrency = "NAD"
	NPR PricelistCurrency = "NPR"
	ANG PricelistCurrency = "ANG"
	AWG PricelistCurrency = "AWG"
	VUV PricelistCurrency = "VUV"
	NZD PricelistCurrency = "NZD"
	NIO PricelistCurrency = "NIO"
	NGN PricelistCurrency = "NGN"
	NOK PricelistCurrency = "NOK"
	PKR PricelistCurrency = "PKR"
	PAB PricelistCurrency = "PAB"
	PGK PricelistCurrency = "PGK"
	PYG PricelistCurrency = "PYG"
	PEN PricelistCurrency = "PEN"
	PHP PricelistCurrency = "PHP"
	QAR PricelistCurrency = "QAR"
	RUB PricelistCurrency = "RUB"
	RWF PricelistCurrency = "RWF"
	SHP PricelistCurrency = "SHP"
	STD PricelistCurrency = "STD"
	SAR PricelistCurrency = "SAR"
	SCR PricelistCurrency = "SCR"
	SLL PricelistCurrency = "SLL"
	SGD PricelistCurrency = "SGD"
	VND PricelistCurrency = "VND"
	SOS PricelistCurrency = "SOS"
	ZAR PricelistCurrency = "ZAR"
	SSP PricelistCurrency = "SSP"
	SZL PricelistCurrency = "SZL"
	SEK PricelistCurrency = "SEK"
	CHF PricelistCurrency = "CHF"
	SYP PricelistCurrency = "SYP"
	THB PricelistCurrency = "THB"
	TOP PricelistCurrency = "TOP"
	TTD PricelistCurrency = "TTD"
	AED PricelistCurrency = "AED"
	TND PricelistCurrency = "TND"
	UGX PricelistCurrency = "UGX"
	MKD PricelistCurrency = "MKD"
	EGP PricelistCurrency = "EGP"
	GBP PricelistCurrency = "GBP"
	TZS PricelistCurrency = "TZS"
	USD PricelistCurrency = "USD"
	UYU PricelistCurrency = "UYU"
	UZS PricelistCurrency = "UZS"
	WST PricelistCurrency = "WST"
	YER PricelistCurrency = "YER"
	TWD PricelistCurrency = "TWD"
	CUC PricelistCurrency = "CUC"
	ZWL PricelistCurrency = "ZWL"
	TMT PricelistCurrency = "TMT"
	GHS PricelistCurrency = "GHS"
	VEF PricelistCurrency = "VEF"
	SDG PricelistCurrency = "SDG"
	UYI PricelistCurrency = "UYI"
	RSD PricelistCurrency = "RSD"
	MZN PricelistCurrency = "MZN"
	AZN PricelistCurrency = "AZN"
	RON PricelistCurrency = "RON"
	CHE PricelistCurrency = "CHE"
	CHW PricelistCurrency = "CHW"
	TRY PricelistCurrency = "TRY"
	XAF PricelistCurrency = "XAF"
	XCD PricelistCurrency = "XCD"
	XOF PricelistCurrency = "XOF"
	XPF PricelistCurrency = "XPF"
	XBA PricelistCurrency = "XBA"
	XBB PricelistCurrency = "XBB"
	XBC PricelistCurrency = "XBC"
	XBD PricelistCurrency = "XBD"
	XAU PricelistCurrency = "XAU"
	XDR PricelistCurrency = "XDR"
	XAG PricelistCurrency = "XAG"
	XPT PricelistCurrency = "XPT"
	XPD PricelistCurrency = "XPD"
	XUA PricelistCurrency = "XUA"
	ZMW PricelistCurrency = "ZMW"
	SRD PricelistCurrency = "SRD"
	MGA PricelistCurrency = "MGA"
	COU PricelistCurrency = "COU"
	AFN PricelistCurrency = "AFN"
	TJS PricelistCurrency = "TJS"
	AOA PricelistCurrency = "AOA"
	BYR PricelistCurrency = "BYR"
	BGN PricelistCurrency = "BGN"
	CDF PricelistCurrency = "CDF"
	BAM PricelistCurrency = "BAM"
	EUR PricelistCurrency = "EUR"
	MXV PricelistCurrency = "MXV"
	UAH PricelistCurrency = "UAH"
	GEL PricelistCurrency = "GEL"
	BOV PricelistCurrency = "BOV"
	PLN PricelistCurrency = "PLN"
	BRL PricelistCurrency = "BRL"
	CLF PricelistCurrency = "CLF"
	XSU PricelistCurrency = "XSU"
	USN PricelistCurrency = "USN"
)

// All allowed values of PricelistCurrency enum
var AllowedPricelistCurrencyEnumValues = []PricelistCurrency{
	"XXX",
	"ALL",
	"DZD",
	"ARS",
	"AUD",
	"BSD",
	"BHD",
	"BDT",
	"AMD",
	"BBD",
	"BMD",
	"BTN",
	"BOB",
	"BWP",
	"BZD",
	"SBD",
	"BND",
	"MMK",
	"BIF",
	"KHR",
	"CAD",
	"CVE",
	"KYD",
	"LKR",
	"CLP",
	"CNY",
	"COP",
	"KMF",
	"CRC",
	"HRK",
	"CUP",
	"CZK",
	"DKK",
	"DOP",
	"SVC",
	"ETB",
	"ERN",
	"FKP",
	"FJD",
	"DJF",
	"GMD",
	"GIP",
	"GTQ",
	"GNF",
	"GYD",
	"HTG",
	"HNL",
	"HKD",
	"HUF",
	"ISK",
	"INR",
	"IDR",
	"IRR",
	"IQD",
	"ILS",
	"JMD",
	"JPY",
	"KZT",
	"JOD",
	"KES",
	"KPW",
	"KRW",
	"KWD",
	"KGS",
	"LAK",
	"LBP",
	"LSL",
	"LRD",
	"LYD",
	"LTL",
	"MOP",
	"MWK",
	"MYR",
	"MVR",
	"MRO",
	"MUR",
	"MXN",
	"MNT",
	"MDL",
	"MAD",
	"OMR",
	"NAD",
	"NPR",
	"ANG",
	"AWG",
	"VUV",
	"NZD",
	"NIO",
	"NGN",
	"NOK",
	"PKR",
	"PAB",
	"PGK",
	"PYG",
	"PEN",
	"PHP",
	"QAR",
	"RUB",
	"RWF",
	"SHP",
	"STD",
	"SAR",
	"SCR",
	"SLL",
	"SGD",
	"VND",
	"SOS",
	"ZAR",
	"SSP",
	"SZL",
	"SEK",
	"CHF",
	"SYP",
	"THB",
	"TOP",
	"TTD",
	"AED",
	"TND",
	"UGX",
	"MKD",
	"EGP",
	"GBP",
	"TZS",
	"USD",
	"UYU",
	"UZS",
	"WST",
	"YER",
	"TWD",
	"CUC",
	"ZWL",
	"TMT",
	"GHS",
	"VEF",
	"SDG",
	"UYI",
	"RSD",
	"MZN",
	"AZN",
	"RON",
	"CHE",
	"CHW",
	"TRY",
	"XAF",
	"XCD",
	"XOF",
	"XPF",
	"XBA",
	"XBB",
	"XBC",
	"XBD",
	"XAU",
	"XDR",
	"XAG",
	"XPT",
	"XPD",
	"XUA",
	"ZMW",
	"SRD",
	"MGA",
	"COU",
	"AFN",
	"TJS",
	"AOA",
	"BYR",
	"BGN",
	"CDF",
	"BAM",
	"EUR",
	"MXV",
	"UAH",
	"GEL",
	"BOV",
	"PLN",
	"BRL",
	"CLF",
	"XSU",
	"USN",
}

func (v *PricelistCurrency) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PricelistCurrency(value)
	for _, existing := range AllowedPricelistCurrencyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PricelistCurrency", value)
}

// NewPricelistCurrencyFromValue returns a pointer to a valid PricelistCurrency
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPricelistCurrencyFromValue(v string) (*PricelistCurrency, error) {
	ev := PricelistCurrency(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PricelistCurrency: valid values are %v", v, AllowedPricelistCurrencyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PricelistCurrency) IsValid() bool {
	for _, existing := range AllowedPricelistCurrencyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to pricelistCurrency value
func (v PricelistCurrency) Ptr() *PricelistCurrency {
	return &v
}

type NullablePricelistCurrency struct {
	value *PricelistCurrency
	isSet bool
}

func (v NullablePricelistCurrency) Get() *PricelistCurrency {
	return v.value
}

func (v *NullablePricelistCurrency) Set(val *PricelistCurrency) {
	v.value = val
	v.isSet = true
}

func (v NullablePricelistCurrency) IsSet() bool {
	return v.isSet
}

func (v *NullablePricelistCurrency) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePricelistCurrency(val *PricelistCurrency) *NullablePricelistCurrency {
	return &NullablePricelistCurrency{value: val, isSet: true}
}

func (v NullablePricelistCurrency) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePricelistCurrency) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

