/*
PriceList Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricelist

import (
	"encoding/json"
)

// checks if the PricelistListFullPriceItemsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PricelistListFullPriceItemsResponse{}

// PricelistListFullPriceItemsResponse struct for PricelistListFullPriceItemsResponse
type PricelistListFullPriceItemsResponse struct {
	Items                []PricelistGetFullPriceItem `json:"items,omitempty"`
	NextPageToken        *string                     `json:"nextPageToken,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PricelistListFullPriceItemsResponse PricelistListFullPriceItemsResponse

// NewPricelistListFullPriceItemsResponse instantiates a new PricelistListFullPriceItemsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPricelistListFullPriceItemsResponse() *PricelistListFullPriceItemsResponse {
	this := PricelistListFullPriceItemsResponse{}
	return &this
}

// NewPricelistListFullPriceItemsResponseWithDefaults instantiates a new PricelistListFullPriceItemsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPricelistListFullPriceItemsResponseWithDefaults() *PricelistListFullPriceItemsResponse {
	this := PricelistListFullPriceItemsResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *PricelistListFullPriceItemsResponse) GetItems() []PricelistGetFullPriceItem {
	if o == nil || IsNil(o.Items) {
		var ret []PricelistGetFullPriceItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistListFullPriceItemsResponse) GetItemsOk() ([]PricelistGetFullPriceItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *PricelistListFullPriceItemsResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []PricelistGetFullPriceItem and assigns it to the Items field.
func (o *PricelistListFullPriceItemsResponse) SetItems(v []PricelistGetFullPriceItem) {
	o.Items = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *PricelistListFullPriceItemsResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistListFullPriceItemsResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *PricelistListFullPriceItemsResponse) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *PricelistListFullPriceItemsResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

func (o PricelistListFullPriceItemsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PricelistListFullPriceItemsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PricelistListFullPriceItemsResponse) UnmarshalJSON(data []byte) (err error) {
	varPricelistListFullPriceItemsResponse := _PricelistListFullPriceItemsResponse{}

	err = json.Unmarshal(data, &varPricelistListFullPriceItemsResponse)

	if err != nil {
		return err
	}

	*o = PricelistListFullPriceItemsResponse(varPricelistListFullPriceItemsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		delete(additionalProperties, "nextPageToken")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PricelistListFullPriceItemsResponse) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *PricelistListFullPriceItemsResponse) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullablePricelistListFullPriceItemsResponse struct {
	value *PricelistListFullPriceItemsResponse
	isSet bool
}

func (v NullablePricelistListFullPriceItemsResponse) Get() *PricelistListFullPriceItemsResponse {
	return v.value
}

func (v *NullablePricelistListFullPriceItemsResponse) Set(val *PricelistListFullPriceItemsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePricelistListFullPriceItemsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePricelistListFullPriceItemsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePricelistListFullPriceItemsResponse(val *PricelistListFullPriceItemsResponse) *NullablePricelistListFullPriceItemsResponse {
	return &NullablePricelistListFullPriceItemsResponse{value: val, isSet: true}
}

func (v NullablePricelistListFullPriceItemsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePricelistListFullPriceItemsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
