/*
pricelist/service.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricelist

import (
	"encoding/json"
)

// checks if the PricelistGetPriceListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PricelistGetPriceListRequest{}

// PricelistGetPriceListRequest struct for PricelistGetPriceListRequest
type PricelistGetPriceListRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	Id *string `json:"id,omitempty"`
}

// NewPricelistGetPriceListRequest instantiates a new PricelistGetPriceListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPricelistGetPriceListRequest() *PricelistGetPriceListRequest {
	this := PricelistGetPriceListRequest{}
	return &this
}

// NewPricelistGetPriceListRequestWithDefaults instantiates a new PricelistGetPriceListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPricelistGetPriceListRequestWithDefaults() *PricelistGetPriceListRequest {
	this := PricelistGetPriceListRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *PricelistGetPriceListRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *PricelistGetPriceListRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *PricelistGetPriceListRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PricelistGetPriceListRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricelistGetPriceListRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PricelistGetPriceListRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PricelistGetPriceListRequest) SetId(v string) {
	o.Id = &v
}

func (o PricelistGetPriceListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PricelistGetPriceListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullablePricelistGetPriceListRequest struct {
	value *PricelistGetPriceListRequest
	isSet bool
}

func (v NullablePricelistGetPriceListRequest) Get() *PricelistGetPriceListRequest {
	return v.value
}

func (v *NullablePricelistGetPriceListRequest) Set(val *PricelistGetPriceListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePricelistGetPriceListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePricelistGetPriceListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePricelistGetPriceListRequest(val *PricelistGetPriceListRequest) *NullablePricelistGetPriceListRequest {
	return &NullablePricelistGetPriceListRequest{value: val, isSet: true}
}

func (v NullablePricelistGetPriceListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePricelistGetPriceListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


